load(":library_test.bzl", "library_cc_test")

filegroup(
    name = "test_source",
    srcs = glob(["*.cpp"]),
)

library_cc_test(target = "utility")

library_cc_test(target = "print_base")

library_cc_test(target = "debug_print")

library_cc_test(target = "normal_print")

library_cc_test(target = "numeric")

library_cc_test(target = "segtree")

library_cc_test(target = "warshall_floyd")

library_cc_test(target = "heuristic")
